name: Build
on:
  pull_request:
    branches:
      - main # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
<<<<<<< HEAD
      - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
=======
       - uses: sonarsource/sonarqube-quality-gate-action@master
         timeout-minutes: 5
>>>>>>> 42ced477aa63993350f2b29fd7a839677c8b2d8f
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}